# Generated by Django 3.1.7 on 2021-03-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='음식점 이름')),
                ('description', models.CharField(max_length=255, verbose_name='음식점 소개')),
                ('address', models.CharField(max_length=255, verbose_name='음식점 주소')),
                ('phone_number', models.CharField(max_length=255, verbose_name='음식점 전화번호')),
            ],
            options={
                'verbose_name': '음식점',
                'verbose_name_plural': '음식점',
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='메뉴 이름')),
                ('price', models.IntegerField(verbose_name='메뉴 가격')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'db_table': 'menu',
            },
        ),
    ]
